language: ruby
cache: bundler
bundler_args: --without development
services: mongodb
rvm:
  - 2.4.5
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake test
  - bundle exec rubocop -R
